name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pg401_pyqt/requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile pg401_pyqt/__main__.py --name PG401LaserApp --paths pg401_pyqt

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: PG401LaserApp-exe
          path: dist/PG401LaserApp.exe
